### ISSUE TITLE
Does not work with TypeScript

### ISSUE THREAD

**Issue by fandy** [peterpalau/react-bnb-gallery#2]
I think forbidExtraProps is interfering with TypeScript

```
Type checking in progress...
/Users/fang/choice-kittens/node_modules/airbnb-prop-types/src/forbidExtraProps.js:1
(function (exports, require, module, __filename, __dirname) { import forbidExtraProps from 'prop-types-exact';
                                                                     ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/fang/choice-kittens/node_modules/react-bnb-gallery/dist/react-bnb-gallery.js:5:40)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
/Users/fang/choice-kittens/node_modules/airbnb-prop-types/src/forbidExtraProps.js:1
(function (exports, require, module, __filename, __dirname) { import forbidExtraProps from 'prop-types-exact';
```

**Comment by peterpalau** [comment]
@fandy This is why my tests are not working right now, I don't know if I missing some configuration for Babel 7, but when I run the tests, Jest give me the same error.

**Comment by fandy** [comment]
@peterpalau Hope you find a fix soon. I haven't had any luck fixing it so I'm just converting everything to TS manually on my app. Cool repo! :)

**Comment by peterpalau** [comment]
@fandy I think I was able to fix this error in the last update, reviewing all the configuration of `babel`, `jest`, `babel-jest` and `rollup` packages. 

I will keep the issue open in case it happens again in another environment.
